arch:
- armhf
- armv7
- aarch64
- amd64
- i386
backup: cold
codenotary: mkosmo@gmail.com
description: A SQL database server
image: ghcr.io/mkosmo/hassio-addon-postgresql/{arch}
init: false
map:
- share:rw
name: PostgreSQL
options:
  databases:
  - homeassistant
  logins:
  - password: null
    username: postgres
  - password: null
    username: homeassistant
  max_connections: 20
  rights:
  - database: homeassistant
    username: homeassistant
ports:
  5432/tcp: null
ports_description:
  5432/tcp: PostgreSQL
schema:
  databases:
  - str
  logins:
  - password: password
    username: str
  max_connections: int(1,)
  rights:
  - database: str
    privileges:
    - list(SELECT|INSERT|UPDATE|DELETE|TRUNCATE|REFERENCES|TRIGGER|CREATE|CONNECT|TEMPORARY|EXECUTE|USAGE|SET)?
    username: str
slug: postgresql
startup: system
timeout: 60
tmpfs: true
url: https://github.com/mkosmo/hassio-addons-postgresql/tree/master/postgresql
version: 2deddff
watchdog: tcp://[HOST]:[PORT:5432]
