arch:
- armhf
- armv7
- aarch64
- amd64
- i386
backup: cold
codenotary: mkosmo@gmail.com
description: A PostgreSQL 15 database server
image: ghcr.io/mkosmo/hassio-addon-postgresql15/{arch}
init: false
map:
- share:rw
name: PostgreSQL 15
options:
  databases:
  - homeassistant
  logins:
  - password: null
    username: postgres
  - password: null
    username: homeassistant
  max_connections: 20
  rights:
  - database: homeassistant
    username: homeassistant
ports:
  5432/tcp: null
ports_description:
  5432/tcp: PostgreSQL
schema:
  databases:
  - str
  logins:
  - password: password
    username: str
  max_connections: int(1,)
  rights:
  - database: str
    privileges:
    - list(SELECT|INSERT|UPDATE|DELETE|TRUNCATE|REFERENCES|TRIGGER|CREATE|CONNECT|TEMPORARY|EXECUTE|USAGE|SET)?
    username: str
slug: postgresql15
startup: system
timeout: 60
tmpfs: true
url: 'https://github.com/mkosmo/hassio-addon-postgresql15/tree/master/postgresql15

  '
version: 06bedd5
watchdog: tcp://[HOST]:[PORT:5432]
